### ISSUE TITLE
make acting_user available on the client

### ISSUE THREAD

**Issue by cantonic** [ruby-hyperloop/hyper-mesh#16]
(originally asked in https://gitter.im/reactrb/chat?at=584e1001b4ffd59e3817981f)

 for Devise I am using the following to set the acting_user
```ruby
class ApplicationController < ActionController::Base
  def acting_user
    @acting_user ||= session["warden.user.user.key"] && User.find(session["warden.user.user.key"][0])
  end
end
```
Is this acting_user also available on the client already? If not, how would I get the current_user within a component?

**Comment by catmando** [comment]
We can have the client class `Connection` have a method that returns the current acting user. (i.e. `HyperMesh::Connection.acting_user`

The problem is that we will have to infer the type of acting_user. 

What I propose is that if acting_user is an ActiveRecord model (usually true) and if that model is available on the client then we are all set. 

Otherwise we will use acting_user.to_json on the server, and reconstitute on the client.

What do you think?

**Comment by cantonic** [comment]
Sounds good

**Comment by sfcgeorge** [comment]
Fixed? https://github.com/ruby-hyperloop/hyperloop-devise-tutorial

**Comment by catmando** [comment]
I think that shows a "work around"  it ought be automatic.  but anyway its actually a hyper-operation issue.
